Login
AlexisN94/MyAnimeCompanion pull request #2
Opened 2022-01-11 15:05 UTC by AlexisN94

- Show Login button in Profile fragment if not logged in
- Store token in Encrypted Shared Preferences
- Save user info in database

2022-01-12 10:11 UTC, andre-exd requested changes

2022-01-12 10:11 UTC, andre-exd commented on app/src/main/java/com/alexis/myanimecompanion/TokenStorageManager.kt
> +        if (!hasToken())
use curly brackets or single line if

2022-01-12 10:11 UTC, andre-exd commented on app/src/main/java/com/alexis/myanimecompanion/TokenStorageManager.kt
> +    fun getToken(): DomainToken? {
Consider renaming this as fetchToken() to indicate that is not just returning value from a variable token

2022-01-12 10:11 UTC, andre-exd commented on app/src/main/java/com/alexis/myanimecompanion/TokenStorageManager.kt
> +    fun setToken(domainToken: DomainToken) {
Consider renaming this method as updateToken or something similar

2022-01-12 10:11 UTC, andre-exd commented on app/src/main/java/com/alexis/myanimecompanion/TokenStorageManager.kt
> +            .putString("token", tokenJson)
Can this value be named token_json instead or something similar? jsonToken is a better name for the variable :P

2022-01-12 10:11 UTC, andre-exd commented on app/src/main/java/com/alexis/myanimecompanion/TokenStorageManager.kt
> +            .putString("token", tokenJson)
Consider creating a private constant for field on SharedPreferences to be reused on other places

2022-01-12 10:11 UTC, andre-exd commented on app/src/main/java/com/alexis/myanimecompanion/TokenStorageManager.kt
> +        return jsonAdapter.fromJson(tokenJson)
Can you handle null from tokenJson more explicitly? probably returning a explicit null is better then returning a null from jsonAdapter.fromJson(). Not sure if an exception will happen if tokenJson is null from...

2022-01-12 10:11 UTC, andre-exd commented on app/src/main/java/com/alexis/myanimecompanion/TokenStorageManager.kt
> +        if (domainToken == null)
curly brackets or single line if

2022-01-12 10:11 UTC, andre-exd commented on app/src/main/java/com/alexis/myanimecompanion/TokenStorageManager.kt
> +        if (!hasToken())
Please remove hasToken() and handle null result from sharedPreferences instead. That was only one access to SharedPreferences will happen and you will remove adding methods that are only be used once

2022-01-12 10:11 UTC, andre-exd commented on app/src/main/java/com/alexis/myanimecompanion/data/AnimeRepository.kt
> +        /* TODO return complete? Anime object with fresh domainUser-specific status */
Was this caused by a search and replace? Please revert it please

2022-01-12 10:11 UTC, andre-exd commented on app/src/main/java/com/alexis/myanimecompanion/data/AnimeRepository.kt
> +        if(localUser == null && remoteUserAsDatabaseUser != null) {
Fix formatting

2022-01-12 10:11 UTC, andre-exd commented on app/src/main/java/com/alexis/myanimecompanion/data/AnimeRepository.kt
> +    suspend fun getUser(): DomainUser? {
Rename method to fetchUser()

2022-01-12 10:11 UTC, andre-exd commented on app/src/main/java/com/alexis/myanimecompanion/data/AnimeRepository.kt
> +        val remoteUserAsDatabaseUser = remoteDataSource.getUser()
Is it really necessary to name this as "...AsDatabase..."? Please simplify if you agree

2022-01-12 10:11 UTC, andre-exd commented on app/src/main/java/com/alexis/myanimecompanion/data/AnimeRepository.kt
> +    suspend fun getUser(): DomainUser? {
Or better, name something that indicates that Database will be updated

2022-01-12 10:11 UTC, andre-exd commented on app/src/main/java/com/alexis/myanimecompanion/data/AnimeRepository.kt
> +    fun getAuthorizationUrl(): String {
Either this method or datasource should be renamed. Please make it consistent.

2022-01-12 10:11 UTC, andre-exd commented on app/src/main/java/com/alexis/myanimecompanion/data/LocalDataSource.kt
> +    fun getUser(): DomainUser? {
I believe this is not a responsibility of LocalDataSource. Please consider changing the result to DatabaseUser as the rest of the methods.

2022-01-12 10:11 UTC, andre-exd commented on app/src/main/java/com/alexis/myanimecompanion/data/LocalDataSource.kt
> +    fun clearUser() {
Consider using deleteUser(user: DatabaseUser) instead

2022-01-12 10:11 UTC, andre-exd commented on app/src/main/java/com/alexis/myanimecompanion/data/local/daos/UserDao.kt
> +    @Query("SELECT * FROM DatabaseUser")
This doesn't seem a good approach. Please consider reverting to previous query and store userId in sharedPreferences if needed

2022-01-12 10:11 UTC, andre-exd commented on app/src/main/java/com/alexis/myanimecompanion/data/remote/models/AnimeStatistics.kt
> + * General anime statistics for the domainUser
Search and replace?

2022-01-12 10:11 UTC, andre-exd commented on app/src/main/java/com/alexis/myanimecompanion/domain/DomainToken.kt
> +)
EOF

2022-01-12 10:11 UTC, andre-exd commented on app/src/main/java/com/alexis/myanimecompanion/domain/DomainUser.kt
> +    val username: String? = null,
Can you remove the default values?

2022-01-12 10:11 UTC, andre-exd commented on app/src/main/java/com/alexis/myanimecompanion/ui/profile/ProfileFragment.kt
> +        binding.lifecycleOwner = viewLifecycleOwner
Try to reuse binding.apply {} as on other Fragments

2022-01-12 10:11 UTC, andre-exd commented on app/src/main/java/com/alexis/myanimecompanion/ui/profile/ProfileFragment.kt
> +
Remove extra lines

2022-01-12 10:11 UTC, andre-exd commented on app/src/main/java/com/alexis/myanimecompanion/ui/profile/ProfileViewModel.kt
> +                _loading.postValue(true)
Consider using a call to updatedLoading(true)

2022-01-12 10:11 UTC, andre-exd commented on app/src/main/java/com/alexis/myanimecompanion/ui/profile/ProfileViewModel.kt
> +    private suspend fun getUser() {
Rename method to not created confusion with a getter to user value

2022-01-12 10:11 UTC, andre-exd commented on app/src/main/res/layout/fragment_profile.xml
> +    xmlns:app="http://schemas.android.com/apk/res-auto">
tools:context

2022-01-12 10:11 UTC, andre-exd commented on app/src/main/res/layout/fragment_profile.xml
> +            android:visibility="@{(viewModel.user == null &amp;&amp; !viewModel.loading) ? View.VISIBLE : View.GONE}"
Can't you use a BindingAdapter to transform a boolean into VISIBLE or GONE?

2022-01-12 10:11 UTC, andre-exd commented on app/src/main/res/layout/fragment_profile.xml
> +            android:text="Login"
strings.xml?

2022-01-12 10:11 UTC, andre-exd commented on app/src/main/res/layout/fragment_profile.xml
> +</layout>
EOF

2022-01-12 10:11 UTC, andre-exd commented on app/src/main/res/navigation/nav_graph.xml
>  </navigation>
Consider adding a new line at end of line. Not sure if file might be regenerated and that change be lost...

2022-01-19 09:33 UTC, andre-exd requested changes

2022-01-19 09:33 UTC, andre-exd commented on app/src/main/java/com/alexis/myanimecompanion/TokenStorageManager.kt
> +
Remove extra line

2022-01-19 09:33 UTC, andre-exd commented on app/src/main/java/com/alexis/myanimecompanion/Utils.kt
> +
Remove extra line

2022-01-19 09:33 UTC, andre-exd commented on app/src/main/java/com/alexis/myanimecompanion/Utils.kt
> +}
Please re-add new line at EOF

2022-01-19 09:33 UTC, andre-exd commented on app/src/main/java/com/alexis/myanimecompanion/data/AnimeRepository.kt
> +
Remove extra line

2022-01-19 09:33 UTC, andre-exd commented on app/src/main/java/com/alexis/myanimecompanion/data/UserRepository.kt
> +}
EOF

2022-01-19 09:33 UTC, andre-exd commented on app/src/main/java/com/alexis/myanimecompanion/ui/BindingAdapters.kt
> +}
EOF

2022-01-19 09:33 UTC, andre-exd commented on app/src/main/java/com/alexis/myanimecompanion/ui/BindingAdapters.kt
> +@BindingAdapter("showIfLoggedIn")
Can you change this BindingAdapter to something more generic that accepts a boolean and converts it into a visibility? Something like "visible(boolean: isVisible)"

2022-01-19 09:33 UTC, andre-exd commented on app/src/main/java/com/alexis/myanimecompanion/ui/profile/ProfileViewModel.kt
> +}
EOF

2022-01-19 09:33 UTC, andre-exd commented on app/src/main/java/com/alexis/myanimecompanion/ui/profile/ProfileViewModelFactory.kt
> +
Remove extra line

2022-01-19 10:40 UTC, AlexisN94 commented on app/src/main/java/com/alexis/myanimecompanion/ui/BindingAdapters.kt
> +}
was fixed in base branch

2022-01-19 10:41 UTC, AlexisN94 commented on app/src/main/java/com/alexis/myanimecompanion/ui/profile/ProfileViewModel.kt
> +}
was fixed in base branch

2022-01-19 10:55 UTC, AlexisN94 commented on app/src/main/java/com/alexis/myanimecompanion/ui/BindingAdapters.kt
> +@BindingAdapter("showIfLoggedIn")
If I understood correctly, that would defeat the purpose of using a BindingAdapter; that's what android:visibility does.
I thought about this as well and it occurred to me to check the id of the Group (it's either _group_not_logged_in_ or _group_logged_in_) and set visibility accordingly, but it didn't feel right to tight the adapter with those ids. If you think it's okay though, I can make that change.

2022-01-19 16:26 UTC, andre-exd commented on app/src/main/java/com/alexis/myanimecompanion/ui/BindingAdapters.kt
> +@BindingAdapter("showIfLoggedIn")
The usage of this bindingAdapter would be almost as you had in the beginning:
android:visible="@{viewModel.user != null &amp;&amp; !viewModel.loading}".
In my understanding this should allow to be reused on situations where the boolean value can be validated using a value from viewModel.
Something as: android:visible="@{viewModel.showLoading}"

2022-01-19 16:38 UTC, AlexisN94 commented on app/src/main/java/com/alexis/myanimecompanion/ui/BindingAdapters.kt
> +@BindingAdapter("showIfLoggedIn")
Please check if it's okay now

2022-01-19 18:40 UTC, andre-exd approved these changes

2022-01-27 18:41 UTC, andre-exd requested changes

2022-01-27 18:41 UTC, andre-exd commented on app/src/main/java/com/alexis/myanimecompanion/ui/search/SearchFragment.kt
> +                        this@SearchFragment.viewModel.search()
This doesn't seem correct

2022-01-27 19:05 UTC, AlexisN94 commented on app/src/main/java/com/alexis/myanimecompanion/ui/search/SearchFragment.kt
> +                        this@SearchFragment.viewModel.search()
I don't think it's incorrect, just redundant perhaps, considering that _this@SearchFragment.viewModel_ should be equal to _this@apply.viewModel_ (i.e. _viewModel_)at this point. Maybe I'm missing your point?

2022-02-03 16:30 UTC, andre-exd commented on app/src/main/java/com/alexis/myanimecompanion/ui/search/SearchFragment.kt
> +                        this@SearchFragment.viewModel.search()
I see

2022-02-03 16:31 UTC, andre-exd approved these changes

2022-02-03 16:40 UTC, merged